app/controllers/days_controller.rb, app/controllers/pickups_controller.rb, app/helpers/days_helper.rb, app/views/days/index.html.erb, app/views/days/new.html.erb, app/views/days/show.html.erb, config/routes.rb, db/seeds.rb
Merging in code from Sprint 1 and adding some fun stuff for Sprint 2. Added grouping to Day.index, added filtering to Day.index, added styling and CSS upgrades to Day.new. TODO: merge stuff with Bilal A and change 3 selects to single Rails date input.
=> Sprint 1 day code

app/views/layouts/_login_navbar.html.erb, app/views/layouts/_navbar.html.erb, app/views/pages/about.html.erb
Fixed the logo paths so that they would work on Heroku.
=> Fixed logo paths

app/models/pickup.rb, app/views/reports/donor.html.erb
Updated reports to match information in the new data model
=> Fixed some bugs

app/controllers/application_controller.rb, app/controllers/days_controller.rb, app/controllers/pickups_controller.rb, app/controllers/reports_controller.rb, app/controllers/sessions_controller.rb, app/controllers/users_controller.rb, app/helpers/sessions_helper.rb, app/helpers/users_helper.rb, app/models/user.rb, app/views/layouts/_navbar.html.erb, app/views/pickups/index.html.erb, app/views/sessions/new.html.erb, db/seeds.rb
Login now works, and authentication/authorization has been added to all controllers
=> Get login working

app/assets/stylesheets/spinner.css.scss, app/controllers/days_controller.rb, app/views/days/index.html.erb, app/views/days/new.html.erb, app/views/days/show.html.erb, app/views/layouts/_flash_messages.html.erb, config/routes.rb, test/controllers/days_controller_test.rb, test/fixtures/days.yml, test/fixtures/users.yml, test/test_helper.rb
Nick O and Bilal A updating everything for the days screens including tests, formatting, etc.
=> Updated everything for Days

app/views/days/show.html.erb
Cleaned up the Day.show page to not show the delete button if it is in the past. Also adjusted the table width to have the offset on the right side like it does on the left.
=> Fixed the Day.show page 

app/controllers/users_controller.rb, app/helpers/users_helper.rb, app/views/users/show.html.erb
updated for super admin, made it so users cannot access user pages that dont exist.  Hid superadmin from admin index, added necessary fields to admin 'show' but no functionality just UI.
=> Sprint2 admin

app/assets/stylesheets/custom.css.scss, app/views/reports/donor.html.erb, app/views/reports/truck.html.erb, config/routes.rb
Last merge we did added some text that we didn't catch. Just cleaning that up.
=> Fixed Problems From Merge

app/assets/stylesheets/custom.css.scss
Converted CSS code into SASS. Added nesting and variables for cleaner code.
=> Improved CSS file

app/views/reports/history.html.erb, app/views/reports/truck.html.erb
IE was blocking multiple file downloads so I modified the code to get around this...
=> Can now download multiple files at once on IE

app/controllers/users_controller.rb, app/helpers/users_helper.rb, app/views/users/edit.html.erb, app/views/users/index.html.erb, app/views/users/show.html.erb
Users cannot delete themselves, users cannot go to users that do not exist, superadmin can now update accounts.
=> Test cases

app/controllers/users_controller.rb, app/views/users/index.html.erb, test/controllers/users_controller_test.rb, test/fixtures/users.yml, test/test_helper.rb
added user tests, fixed default flash messages to something more appropriate
=> added tests

app/models/user.rb, app/views/users/show.html.erb
moved place of admin password confirm, added days and pickups
=> made minor changes

app/views/users/show.html.erb
Adding in the file that had merge conflicts
=> Adding in file that caused merge

app/views/days/index.html.erb, app/views/days/new.html.erb, app/views/days/show.html.erb, app/views/layouts/application.html.erb, app/views/pages/about.html.erb, app/views/pickups/edit.html.erb, app/views/pickups/index.html.erb, app/views/pickups/new.html.erb, app/views/pickups/reject.html.erb, app/views/reports/donor.html.erb, app/views/reports/history.html.erb, app/views/reports/index.html.erb, app/views/reports/truck.html.erb, app/views/sessions/new.html.erb, app/views/users/index.html.erb, app/views/users/new.html.erb
Title should now either show "Odyssey | <dynamic-title>" or just plain "Odyssey" if not title is provided
=> Added title on every page. 

app/assets/stylesheets/custom.css.scss, app/views/users/show.html.erb
- Some of the style got removed after the latest changes to Users.show. Just went in and corrected them
- Also added some styling to the 'Delete User' text so it isn't as friendly and welcoming.
=> Fixed Styling On Admin Pages

test/controllers/days_controller_test.rb, test/test_helper.rb
Added some assert_selects to check the title is correct.
=> Updated Days_Test to check for correct titles

app/models/user.rb
Implemented the function to allow superadmin to remove pickups that are older than 6 months with a button click.
=> Implemented 'prune_pickups' for superadmin

app/controllers/users_controller.rb, app/helpers/pickups_helper.rb, app/helpers/users_helper.rb, app/models/user.rb, app/views/users/show.html.erb, config/routes.rb
Also changed show.html.erb to hide the remove user link if an admin is look at their own settings.
=> Fixed prune_pickups so that it redirects to the users index.

app/views/reports/truck.html.erb
Fun!
Hope I don't break anything.
ha... yow, bill
=> 2 char fix to Truck Report title

app/assets/stylesheets/custom.css.scss
- Just adjusted the icon sizes on the help page. Not sure if they look the best yet, but it's a little better.
=> Help Page Styling

app/views/pickups/index.html.erb
Home was the only section with flash messages that were too large, so I went ahead and fixed it up. All the flash messages should look OK and consistent now across the main pages.
=> Fixed Styling of Flash Messages on Home

app/views/pages/about.html.erb, app/views/pickups/index.html.erb, app/views/users/index.html.erb
Added cursor icon for clickable rows, removed extra html style include links from about page that was throwing errors.
=> Minor changes

app/controllers/users_controller.rb, app/views/users/index.html.erb, app/views/users/new.html.erb, app/views/users/show.html.erb
Also added more comments to users controller per in-class discussion.
=> Removed unnecessary HTML tags.

app/views/days/index.html.erb, app/views/pickups/index.html.erb
made links orange in places where the link is within a row and cannot be seen because of row hover styling
=> Small Tweaks

app/views/users/show.html.erb
Footer was offset due to misplaced ruby code. Moved the if super check and now the footer looks fine.
=> Fixed offset footer fix#83

Gemfile.lock, app/views/pages/help.html.erb
Just Help text edits. 
Also, one HTML weeble on the first question.
=> Edited my help text

app/views/reports/donor.html.erb, app/views/reports/truck.html.erb
=> Added timeout before redirect to give second report enough time to download

app/assets/stylesheets/Hexagon.css
Changed almost the entire file for the updated responsive hex tiles.
=> Updated for new Responsive Hex tiles

app/controllers/users_controller.rb
added additional comments for the update action in user controller
=> improved comments

app/views/pages/about.html.erb
Removing loading icon script due to load issues
=> Remove loading script

app/views/pages/about.html.erb
Totally forgot to remove the div linked to the loading script as well.
=> Remove loading div

app/views/pages/about.html.erb
There were a few missing " on the end of several tags for the images.
=> Missing " on end of tags

app/assets/stylesheets/Hexagon.css
The style.css was removed and so the few code bits for the about page need to be added to the Hexagon file
=> Adding Style Code

app/views/pages/about.html.erb
Made minor edits to resolve hexagon images not appearing correctly.
=> Resolving Hexagon Images

app/views/pages/about.html.erb
=> Minor fixes for about

app/assets/stylesheets/custom.css.scss
navbarAbout was duplicated with a larger value than should be used.
=> Removed duplicated code

app/controllers/pickups_controller.rb, app/controllers/users_controller.rb, app/views/days/show.html.erb
=> Nick O fixes #7

app/assets/stylesheets/Hexagon.css.scss
=> Updated Hexagon

app/views/pages/about.html.erb
Added peoples images, and text to the about page
=> Updated About text

app/controllers/days_controller.rb, app/views/days/new.html.erb, app/views/reports/donor.html.erb, app/views/reports/truck.html.erb
several minor tweaks to resolve some issues
=> Nick O fixes #8

app/views/days/new.html.erb, app/views/pickups/edit.html.erb, app/views/pickups/new.html.erb
moved the render of some flash messages that got missed.
=> Nick O fixes #9

app/models/pickup.rb, app/views/reports/donor.html.erb
=> Fixed issues 

db/seeds.rb
=> changed super user_name

app/controllers/sessions_controller.rb
Username is now trimmed when the user attempts to log in.
=> Trim the username on login

.gitignore, app/views/sessions/new.html.erb, config/application.yml
Change login screen: Odyssey V1.1
This is a test. 
thanks... yow, bill
=> Vone point one

app/controllers/pickups_controller.rb, app/controllers/reports_controller.rb, app/views/reports/search.html.erb, config/routes.rb
displaying search results on search page, searches are case sensitive however
=> displaying search results on search page

app/controllers/pickups_controller.rb
creating a new branch to continue work to warn on duplicates
=> beginning work to warn on duplicate pickups

app/controllers/days_controller.rb
added day_notes, updating day table with the day_notes now
=> Schedule notes

app/controllers/pickups_controller.rb, app/views/days/edit.html.erb, app/views/pickups/edit.html.erb, app/views/pickups/new.html.erb
finished adding labels and label colors, made buttons a little prettier
=> Pickup labels

app/views/days/show.html.erb, app/views/pages/help.html.erb, app/views/pickups/edit.html.erb
finished pickups labels and colors, edited help page to tell the users whats new in V1.1
=> changes finalized
